### ISSUE TITLE
Use gulp-load-plugins to simplify imports statements

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#1]
https://github.com/trungnguyenminh1992/tony-frontend-test/blob/ab8975c342d75c3a83afadb83c07fdca896dbb58/gulpfile.js#L10

I recommend using `gulp-load-plugins` so you can simplify the import of plugins that start with `gulp-`. 

for example:

```
import plugins       from 'gulp-load-plugins';
const $ = plugins();

```
.pipe($.sass({
...
});
```

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit   https://github.com/trungnguyenminh1992/tony-frontend-test/commit/3c2a42d5a86433db254657d9786aeaa2504a58fd

**Comment by ghost** [comment]
@trungnguyenminh1992 LGTM. Closing for now
