### ISSUE TITLE
README.md should include project setup instructions

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#2]
Good job including readme in project. Please also include info about project dependencies (npm version, etc.) and info about how to set up

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit  https://github.com/trungnguyenminh1992/tony-frontend-test/commit/dc04ba89d8fb8683869260fd40d1fb05dec672b0

**Comment by ghost** [comment]
@trungnguyenminh1992 Good job. Thanks for updating. Closing
