### ISSUE TITLE
remove dist folder from repository 

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#3]
it is best practice to exclude dist folder from repository using git ignore. Dist folder is created locally when gulp tasks are run so it will be modified

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit e8168f9

**Comment by ghost** [comment]
@trungnguyenminh1992 Confirmed removed. Closing
