### ISSUE TITLE
include language attribute in html tag

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#4]
https://github.com/trungnguyenminh1992/tony-frontend-test/blob/ab8975c342d75c3a83afadb83c07fdca896dbb58/dist/index.html#L1

it's best practice to include language attribute in HTML tag

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit  https://github.com/trungnguyenminh1992/tony-frontend-test/commit/9d14cac6928996aeabb92c96181521f1fdb474a0

**Comment by ghost** [comment]
@trungnguyenminh1992 Thanks. LGTM, closing
