### ISSUE TITLE
remove blank posts.css file

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#5]
`app/css/sections/posts.css`

file appears empty. Best practice is to not commit blank, empty files to repository

**Comment by ghost** [comment]
@trungnguyenminh1992 Actually, it is strange to have a css folder in the app folder when you already have scss folder.

css should be compiled to dist folder and CSS should not be included in app folder.

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit e8168f9

**Comment by ghost** [comment]
@trungnguyenminh1992 confirmed removed. Closing
