### ISSUE TITLE
Follow best practices for bracket and rule declaration

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#6]
https://github.com/trungnguyenminh1992/tony-frontend-test/blob/ab8975c342d75c3a83afadb83c07fdca896dbb58/app/css/styles.css#L24

It is best practice to separate new rules with a new line.
Also closing bracket should begin on a new line.

```
.rule-one {
  ...
}
// new line
.rule-two {
...
}
```

**Comment by ghost** [comment]
@trungnguyenminh1992 I see the issue now. You included css folder in app directory. Please remove css folder from you app directory since styles are declared in scss folder

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit  https://github.com/trungnguyenminh1992/tony-frontend-test/commit/e8168f9d333f10085d59ba95d882790aca25cb23

**Comment by ghost** [comment]
@trungnguyenminh1992 confirmed removed from repository. Closing
