### ISSUE TITLE
include full class name instead of shorthand

### ISSUE THREAD

**Issue by ghost** [trungnguyenminh1992/tony-frontend-test#7]
https://github.com/trungnguyenminh1992/tony-frontend-test/blob/ab8975c342d75c3a83afadb83c07fdca896dbb58/app/scss/_base.scss#L27

It is best practice to use full class name instead of shorthand because searching for class names is easier.

`&__title` should be `row__title`

**Comment by ghost** [comment]
@trungnguyenminh1992 also, I notice that in your html markup you don't have `row__title` it is written as `row--title`. Please confirm

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, Hi, the '&__title' you see in '_base.scss' belong to '.section'.
In html markup, it contains class 'section__title' in line 23, the class 'row--title' you see belong to another style '.row'. Thank you.

**Comment by ghost** [comment]
@trungnguyenminh1992 I see, thanks for clarification. Please proceed with updating classnames to use full name instead of shorthand

**Comment by trungnguyenminh1992** [comment]
@hyakurendev, I updated code follow your suggestion. Please take a look at commit  https://github.com/trungnguyenminh1992/tony-frontend-test/commit/a456e5bf0c9ae99d431526415928da7730c01754

**Comment by ghost** [comment]
@trungnguyenminh1992 This is much easier to read and maintain. Good job. Closing
